name: CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo mkdir --parents /usr/local/share/ca-certificates/Yandex
        sudo wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" --output-document /usr/local/share/ca-certificates/Yandex/RootCA.crt
        sudo wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem" --output-document /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
        sudo chmod 655 /usr/local/share/ca-certificates/Yandex/RootCA.crt /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
        sudo update-ca-certificates

        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run parser
      run: python data/parser.py
      env:
        CLICKHOUSE_HOST: ${{ secrets.CLICKHOUSE_HOST }}
        CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
        CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
